### ISSUE TITLE
Separate assembly for NUnit extensibility

### ISSUE THREAD

**Issue by CharliePoole** [nunit/nunit-console#1049]
This feature was first developed as "Engine Extensibility" so the implementation is embodied in an engine service. This makes it next to impossible to use extensibility in other places, like in the console runner, third party runners and even in our own agents.

I propose that we create a separate assembly... NUnit.Extensibility to contain most of the implementation... the existing engine service would simply use an API to access the implementation details.

As a subsquent improvement (but not part of this issue) we could implement the IFrameworkDriverFactory extension in nunit.core using the API directly, without need for full access to engine services.

I'm calling this an idea for now and asking for @nunit/engine-team  discussion.

**Comment by CharliePoole** [comment]
@jnm2 @mikkelbu Any thoughts on this?

**Comment by CharliePoole** [comment]
I'm fleshing this out further and starting to work on it. Hoping that it will make enough sense to engender comments as I get more into the details!

Here's how I break this down stepwise...

Non-Breaking Changes:
- [ ] Split ExtensionService into two classes, both still in nunit.engine.core. ExtensionService will aim specifically at handling extensions to the engine while a new class, tentatively named ExtensionManager, will provide a lower-level interface for the implementation.
- [ ] Make DriverService use ExtensionManager directly rather than ExtensionService and make it no longer a service itself.
- [ ] Once ExtensionService is the only service left in nunit.engine.core and is no longer used there, move it to nunit.engine along with all the service infrastructure classes.
- [ ] Move ExtensionManager to a separate assembly along with it's supporting classes.

Breaking Changes:
- [ ] Modify engine package to use the tools directory and have NUnit-Console load the engine as an extension using ExtensionManager.
